INCBASE = -I..
FLAGS = -g -O2 -std=c++11

searcher: main.cpp
	g++ $(FLAGS) $(INCBASE) -o searcher main.cpp

#lister.o: lister.h lister.cpp
#	g++ $(FLAGS) $(INCBASE) -c lister.cpp
#
#indexer.o: indexer.h indexer.cpp
#	g++ $(FLAGS) $(INCBASE) -c indexer.cpp
#
clear:
	rm *.o

